### ISSUE TITLE
grunt-skylint build error

### ISSUE THREAD

**Issue by Blackbaud-JoePrice** [blackbaud/Blackbaud-CRM-SKY#3]
While following the documented build steps, `grunt buildcustom` fails with the following error during the skylint task:

```
PS C:\code\Blackbaud-CRM-SKY\Blackbaud.AppFx.MajorGiving.Mobile.Sky> grunt buildcustom
Running Blackbaud.AppFx.MajorGiving.Mobile.Sky/gruntfile.js
IsDesktopBuild: undefined
IsDesktopBuild was not false. Defaulting true.
SKYUX Setting current environment: local

Running "jshint:all" (jshint) task
>> 91 files lint free.

Running "jscs:all" (jscs) task
>> 91 files without code style errors.

Running "skylint:files" (skylint) task
Testing 18 file(s)...
Fatal error: Callback must be a function
```

**Comment by Blackbaud-DarrylEychner** [comment]
Hey, Joe! I followed the steps and did see a jslint error on step 6, asking me to remove the customizableRoot injection. I did and then it built successfully. I've added a note in the documentation. I did not, however, see any skylint errors. Are you still getting that?

**Comment by Blackbaud-JoePrice** [comment]
Hi Darryl, thanks for the followup. I am still getting the skylint error "callback must be a function". My workaround was to replace https://github.com/blackbaud/Blackbaud-CRM-SKY/blob/master/Blackbaud.AppFx.MajorGiving.Mobile.Sky/gruntfile.js#L410 with `grunt.registerTask('lint', ['jshint', 'jscs']);` but that is just bypassing skylint altogether.

**Comment by Blackbaud-DarrylEychner** [comment]
Can you verify that you have nodeJS version 6.10.0 installed? You can do this by running `node -v` from an administrator command prompt.

**Comment by Blackbaud-JoePrice** [comment]
Ah, that's probably it. I'm running 10.14.2.

**Comment by Blackbaud-DarrylEychner** [comment]
Do you still see the issue when you install and use 6.10.0?

**Comment by Blackbaud-JoePrice** [comment]
With 6.10.0, it doesn't thrown an error but it doesn't appear to complete the rest of the buildcustom tasks of 'default' and 'copycustom'. Here is the complete log for reference.

```
Running Blackbaud.AppFx.MajorGiving.Mobile.Sky/gruntfile.js
IsDesktopBuild: undefined
IsDesktopBuild was not false. Defaulting true.
SKYUX Setting current environment: local

Running "jshint:all" (jshint) task
>> 91 files lint free.

Running "jscs:all" (jscs) task
>> 91 files without code style errors.

Running "skylint:files" (skylint) task
```

**Comment by Blackbaud-DarrylEychner** [comment]
I am unable to duplicate this error locally, so my ability to troubleshoot may be limited. Are you seeing the process hang on that step? Or does it complete without performing the others (or at least printing to the console)? It might be worth checking versions of other software prerequisites to ensure that you're running the same version we use to test and develop the software.

**Comment by Blackbaud-JoePrice** [comment]
It appears to stop executing tasks at the skylint step. If you're able to get past he skylint pieces without issue than it has to be something local to my setup. Appreciate your input and confirmation that it is working for others!
